### ISSUE TITLE
What is difference between this project and caiobiodere?

### ISSUE THREAD

**Issue by rlam3** [g4b0/framework7-cordova-integration#1]
What is the difference between this project and

https://github.com/caiobiodere/cordova-template-framework7-vue-webpack

**Comment by g4b0** [comment]
Mine is a dead project, since I noticed that what my project does was already done by https://github.com/framework7io/framework7-cli-template-tabs

I don't know https://github.com/caiobiodere/cordova-template-framework7-vue-webpack
